# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20170407_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioner',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
