# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20170409_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioner',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
